apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
  containers:
    - name: app
      image: alpine
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: nfs-storage
          mountPath: "/mnt/nfs"
